### ISSUE TITLE
Add visual material

### ISSUE THREAD

**Issue by cpinter** [EBATINCA/RadiotherapyTransformsIEC#15]
Need to find a good place for the visual material
https://gist.github.com/TrosnyogoSzakoca/f84a973e7120a90f0cc21d7c6ce6e65e

@ferdymercury Where do you think this should go? In the readme or a separate `.md`? What about the gifs? I wouldn't "pollute" and expand the library with images, how about adding them as release?

**Comment by ferdymercury** [comment]
I agree it's better not to pollute. Thus I think that adding them to the Wiki of the github repo would be ideal, there it does not matter to store as many gifs as we want. Then, from the main repo, in the README.md we can add a link to the wiki.

A potential upgrade would be to 'resave' the gifs by clicking the new option "Fix 3D camera", and remove the sentence `Please note that, in these animated images, the "camera" is attached to the patient reference system (DICOM CT), and not to the fixed reference system Xf, Yf, Zf (i.e. the treatment room). Thus, couch rotations are visualized as if the room were moving away from the 'patient at rest', while in reality, the patient would be moving with respect to the room.`

**Comment by cpinter** [comment]
Right, I forgot about the wiki. I'll publish what we have there.

The upgrade sounds good. I'll create a ticket for that just so that it's more explicit.

**Comment by cpinter** [comment]
https://github.com/EBATINCA/RadiotherapyTransformsIEC/wiki/IEC-coordinate-systems-summary
