### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by ferdymercury** [EBATINCA/RadiotherapyTransformsIEC#5]
@TrosnyogoSzakoca the opensource license file is missing in the repo, use predefined templates

**Comment by cpinter** [comment]
Which one would you choose? Apache 2? BSD-3?

**Comment by ferdymercury** [comment]
Maybe lgplv3?

**Comment by cpinter** [comment]
It cannot be because then SlicerRT cannot use it.

Update: Maybe yes, I thought it was like gpl. Need to look into it. Around Slicer everything is published under the Slicer license (BSD-style), BSD, or Apache.

**Comment by ferdymercury** [comment]
Thanks!

From https://opensource.stackexchange.com/questions/6698/can-i-use-code-from-an-lgpl-v2-licenced-project-in-a-bsd-3-clause-licenced-proje

```
A LGPL-licensed library can be used by a BSD-licensed project, as long as users (incl. all end users) are free to study and swap out the LGPLed parts of the software. This means either dynamically linking to the LGPL library, or distributing your project in a way that allows it to be relinked with a different version.
```

**Comment by cpinter** [comment]
Please think about how important it is to choose a certain license. The less compatibility issues we have the better, so I'd encourage to use something that does not need extra maintenance and consideration.

**Comment by ferdymercury** [comment]
I like a bit more LGPL, but if that poses problems, ok with BSD3
